Adding a function to get an author's email address.
slothluvchunk/wp-components pull request #1
Opened 2019-12-11 18:06 UTC by bquade-cpr

Excluding byline manager profiles for now because I don't think they have an email address and I don't know how to test it.

2019-12-11 19:08 UTC, CPROps requested changes
Two suggestions - one is not blocking, just a recommendation. 
Getting rid of the commented-out code will also fix the Travis build error. 

Other than that, looks/functions great. Thanks!

2019-12-11 19:08 UTC, CPROps commented on inc/wp-components/traits/trait-author.php
> +			*/
We should remove this commented chunk before going live.

2019-12-11 19:08 UTC, CPROps commented on inc/wp-components/traits/trait-author.php
> +				break;
Not a blocker - but you might want a default case, here - for other roles to break on.

2019-12-12 17:22 UTC, slothluvchunk approved these changes

2019-12-12 17:29 UTC, CPROps approved these changes
🐴

2019-12-12 17:30 UTC, CPROps commented
PR approved, merging.

2019-12-12 17:30 UTC, merged